# Generated by Django 5.1.6 on 2025-03-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route_no', models.CharField(max_length=20)),
                ('stop_name', models.CharField(max_length=100)),
                ('stop_latitude', models.FloatField()),
                ('stop_longitude', models.FloatField()),
                ('fare_stage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.CharField(max_length=20)),
                ('schedule_no', models.CharField(max_length=20)),
                ('trip_no', models.IntegerField()),
                ('order_sequence', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('via', models.CharField(blank=True, max_length=100, null=True)),
                ('service_type', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'unique_together': {('schedule_no', 'trip_no', 'order_sequence')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trip_no', models.IntegerField()),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('schedule_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='bus_route.schedule')),
            ],
            options={
                'unique_together': {('date', 'schedule_no', 'trip_no')},
            },
        ),
    ]
